[metadata]
name = c65of
summary = OpenFlow 1.3 protocol, packet and controller library with no runtime dependencies
license = Apache-2
author = c65sdn
home_page = https://github.com/c65sdn/c65of
platform = any
classifier =
    Development Status :: 3 - Alpha
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Topic :: System :: Networking
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Operating System :: Unix
keywords =
    openflow
    openvswitch
    sdn

[files]
packages =
    c65of

[bdist_wheel]
universal = 0

[egg_info]
tag_build =
tag_date = 0
