"""Differential test: c65of OpenFlow 1.3 constants against the os-ken reference.

os-ken is a test-only oracle. Every public scalar defined by the reference
ofproto modules must exist in c65of with an identical value, except the OXM
names generated by a separate module.
"""

# Copyright (C) 2026 The c65sdn Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re

import pytest

from os_ken.ofproto import ether as ref_ether
from os_ken.ofproto import inet as ref_inet
from os_ken.ofproto import ofproto_common as ref_common
from os_ken.ofproto import ofproto_v1_3 as ref_ofp

from c65of.ofproto import consts
from c65of.ofproto import ether
from c65of.ofproto import inet

SCALARS = (int, str, float)

# Generated elsewhere from the OXM field table, deliberately absent from consts.
EXCLUDED = re.compile(r"^(OXM_OF_|OFPXMT_OFB_)")

# The two reference modules disagree: ofproto_common says 6653 (IANA, and what
# os-ken's own controller binds), ofproto_v1_3 ends with a stale 6633. c65of
# takes 6653 and keeps the old value under OFP_TCP_PORT_OLD.
CONFLICTS = {(ref_common, "OFP_TCP_PORT"), (ref_ofp, "OFP_TCP_PORT")}


def _scalars(module):
    return {
        name: value
        for name, value in vars(module).items()
        if not name.startswith("_")
        and isinstance(value, SCALARS)
        and not EXCLUDED.match(name)
    }


@pytest.mark.parametrize(
    "ref, own",
    [
        (ref_ofp, consts),
        (ref_common, consts),
        (ref_ether, ether),
        (ref_inet, inet),
    ],
    ids=["ofproto_v1_3", "ofproto_common", "ether", "inet"],
)
def test_constants_match_reference(ref, own):
    """Every public reference scalar is present in c65of with the same value."""
    missing = []
    differing = []
    for name, want in _scalars(ref).items():
        if (ref, name) in CONFLICTS:
            continue
        if not hasattr(own, name):
            missing.append(name)
            continue
        got = getattr(own, name)
        if got != want or not isinstance(got, type(want)):
            differing.append(f"{name}: {got!r} != {want!r}")
    assert not (missing or differing), "\n".join(
        [f"{ref.__name__} vs {own.__name__}"]
        + [f"missing: {name}" for name in missing]
        + [f"differs: {diff}" for diff in differing]
    )


def test_conflicting_names_are_defined():
    """Names the two reference modules disagree on still resolve to a scalar."""
    for _, name in CONFLICTS:
        assert isinstance(getattr(consts, name), SCALARS)
    assert consts.OFP_SSL_PORT == ref_common.OFP_SSL_PORT == 6653
    assert consts.OFP_TCP_PORT == ref_common.OFP_TCP_PORT == 6653
    assert consts.OFP_TCP_PORT_OLD == ref_ofp.OFP_TCP_PORT == 6633


@pytest.mark.parametrize("field", [0, 1, 6, 39, 100, 0x7F])
@pytest.mark.parametrize("length", [1, 2, 4, 6, 8, 16, 0x3F])
def test_oxm_tlv_header_helpers(field, length):
    """OXM TLV header pack/extract helpers agree with the reference."""
    header = consts.oxm_tlv_header(field, length)
    header_w = consts.oxm_tlv_header_w(field, length)
    assert header == ref_ofp.oxm_tlv_header(field, length)
    assert header_w == ref_ofp.oxm_tlv_header_w(field, length)
    for value in (header, header_w):
        hasmask = consts.oxm_tlv_header_extract_hasmask(value)
        assert hasmask == ref_ofp.oxm_tlv_header_extract_hasmask(value)
        extracted = consts.oxm_tlv_header_extract_length(value)
        assert extracted == ref_ofp.oxm_tlv_header_extract_length(value)
    assert consts.oxm_tlv_header_extract_hasmask(header) == 0
    assert consts.oxm_tlv_header_extract_hasmask(header_w) == 1
    assert consts.oxm_tlv_header_extract_length(header) == length
    assert consts.oxm_tlv_header_extract_length(header_w) == length
