"""OpenFlow 1.3 wire protocol constants.

Enumerations, flags, error codes and ``struct`` pack strings for the OpenFlow
1.3.5 wire format, plus the OXM TLV header helpers. Values are the protocol's,
not this library's; names follow the specification.
"""

# Copyright (C) 2026 The c65sdn Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pylint: disable=too-many-lines
from struct import calcsize

# struct ofp_header
OFP_HEADER_PACK_STR = "!BBHI"
OFP_HEADER_SIZE = 8
assert calcsize(OFP_HEADER_PACK_STR) == OFP_HEADER_SIZE

# enum ofp_type
OFPT_HELLO = 0
OFPT_ERROR = 1
OFPT_ECHO_REQUEST = 2
OFPT_ECHO_REPLY = 3
OFPT_EXPERIMENTER = 4

OFPT_FEATURES_REQUEST = 5
OFPT_FEATURES_REPLY = 6
OFPT_GET_CONFIG_REQUEST = 7
OFPT_GET_CONFIG_REPLY = 8
OFPT_SET_CONFIG = 9

OFPT_PACKET_IN = 10
OFPT_FLOW_REMOVED = 11
OFPT_PORT_STATUS = 12

OFPT_PACKET_OUT = 13
OFPT_FLOW_MOD = 14
OFPT_GROUP_MOD = 15
OFPT_PORT_MOD = 16
OFPT_TABLE_MOD = 17

OFPT_MULTIPART_REQUEST = 18
OFPT_MULTIPART_REPLY = 19

OFPT_BARRIER_REQUEST = 20
OFPT_BARRIER_REPLY = 21
OFPT_QUEUE_GET_CONFIG_REQUEST = 22
OFPT_QUEUE_GET_CONFIG_REPLY = 23

OFPT_ROLE_REQUEST = 24
OFPT_ROLE_REPLY = 25

OFPT_GET_ASYNC_REQUEST = 26
OFPT_GET_ASYNC_REPLY = 27
OFPT_SET_ASYNC = 28

OFPT_METER_MOD = 29

# struct ofp_port
OFP_MAX_PORT_NAME_LEN = 16
OFP_ETH_ALEN = 6
OFP_ETH_ALEN_STR = str(OFP_ETH_ALEN)
_OFP_PORT_PACK_STR = (
    "I4x"
    + OFP_ETH_ALEN_STR
    + "s"
    + "2x"
    + str(OFP_MAX_PORT_NAME_LEN)
    + "s"
    + "IIIIIIII"
)
OFP_PORT_PACK_STR = "!" + _OFP_PORT_PACK_STR
OFP_PORT_SIZE = 64
assert calcsize(OFP_PORT_PACK_STR) == OFP_PORT_SIZE

# enum ofp_port_config
OFPPC_PORT_DOWN = 1 << 0
OFPPC_NO_RECV = 1 << 2
OFPPC_NO_FWD = 1 << 5
OFPPC_NO_PACKET_IN = 1 << 6

# enum ofp_port_state
OFPPS_LINK_DOWN = 1 << 0
OFPPS_BLOCKED = 1 << 1
OFPPS_LIVE = 1 << 2

# enum ofp_port_no
OFPP_MAX = 0xFFFFFF00
OFPP_IN_PORT = 0xFFFFFFF8
OFPP_TABLE = 0xFFFFFFF9
OFPP_NORMAL = 0xFFFFFFFA
OFPP_FLOOD = 0xFFFFFFFB
OFPP_ALL = 0xFFFFFFFC
OFPP_CONTROLLER = 0xFFFFFFFD
OFPP_LOCAL = 0xFFFFFFFE
OFPP_ANY = 0xFFFFFFFF

OFPQ_ALL = 0xFFFFFFFF

# enum ofp_port_features
OFPPF_10MB_HD = 1 << 0
OFPPF_10MB_FD = 1 << 1
OFPPF_100MB_HD = 1 << 2
OFPPF_100MB_FD = 1 << 3
OFPPF_1GB_HD = 1 << 4
OFPPF_1GB_FD = 1 << 5
OFPPF_10GB_FD = 1 << 6
OFPPF_40GB_FD = 1 << 7
OFPPF_100GB_FD = 1 << 8
OFPPF_1TB_FD = 1 << 9
OFPPF_OTHER = 1 << 10
OFPPF_COPPER = 1 << 11
OFPPF_FIBER = 1 << 12
OFPPF_AUTONEG = 1 << 13
OFPPF_PAUSE = 1 << 14
OFPPF_PAUSE_ASYM = 1 << 15

# struct ofp_packet_queue
OFP_PACKET_QUEUE_PACK_STR = "!IIH6x"
OFP_PACKET_QUEUE_SIZE = 16
assert calcsize(OFP_PACKET_QUEUE_PACK_STR) == OFP_PACKET_QUEUE_SIZE

# enum ofp_queue_properties
OFPQT_MIN_RATE = 1
OFPQT_MAX_RATE = 2
OFPQT_EXPERIMENTER = 0xFFFF

# struct ofp_queue_prop_header
OFP_QUEUE_PROP_HEADER_PACK_STR = "!HH4x"
OFP_QUEUE_PROP_HEADER_SIZE = 8
assert calcsize(OFP_QUEUE_PROP_HEADER_PACK_STR) == OFP_QUEUE_PROP_HEADER_SIZE

# struct ofp_queue_prop_min_rate
OFP_QUEUE_PROP_MIN_RATE_PACK_STR = "!H6x"
OFP_QUEUE_PROP_MIN_RATE_SIZE = 16
assert (
    calcsize(OFP_QUEUE_PROP_MIN_RATE_PACK_STR) + OFP_QUEUE_PROP_HEADER_SIZE
) == OFP_QUEUE_PROP_MIN_RATE_SIZE

# struct ofp_queue_prop_max_rate
OFP_QUEUE_PROP_MAX_RATE_PACK_STR = "!H6x"
OFP_QUEUE_PROP_MAX_RATE_SIZE = 16
assert (
    calcsize(OFP_QUEUE_PROP_MAX_RATE_PACK_STR) + OFP_QUEUE_PROP_HEADER_SIZE
) == OFP_QUEUE_PROP_MAX_RATE_SIZE

# struct ofp_queue_prop_experimenter
OFP_QUEUE_PROP_EXPERIMENTER_PACK_STR = "!I4x"
OFP_QUEUE_PROP_EXPERIMENTER_SIZE = 16
assert (
    calcsize(OFP_QUEUE_PROP_EXPERIMENTER_PACK_STR) + OFP_QUEUE_PROP_HEADER_SIZE
) == OFP_QUEUE_PROP_EXPERIMENTER_SIZE

# struct ofp_match
_OFP_MATCH_PACK_STR = "HHBBBB"
OFP_MATCH_PACK_STR = "!" + _OFP_MATCH_PACK_STR
OFP_MATCH_SIZE = 8
assert calcsize(OFP_MATCH_PACK_STR) == OFP_MATCH_SIZE

# enum ofp_match_type
OFPMT_STANDARD = 0
OFPMT_OXM = 1

# enum ofp_oxm_class
OFPXMC_NXM_0 = 0x0000
OFPXMC_NXM_1 = 0x0001
OFPXMC_OPENFLOW_BASIC = 0x8000
OFPXMC_EXPERIMENTER = 0xFFFF

# enum ofp_vlan_id
OFPVID_PRESENT = 0x1000
OFPVID_NONE = 0x0000

# enum ofp_ipv6exthdr_flags
OFPIEH_NONEXT = 1 << 0
OFPIEH_ESP = 1 << 1
OFPIEH_AUTH = 1 << 2
OFPIEH_DEST = 1 << 3
OFPIEH_FRAG = 1 << 4
OFPIEH_ROUTER = 1 << 5
OFPIEH_HOP = 1 << 6
OFPIEH_UNREP = 1 << 7
OFPIEH_UNSEQ = 1 << 8

# ofp_oxm_experimenter_header
OFP_OXM_EXPERIMENTER_HEADER_PACK_STR = "!II"
OFP_OXM_EXPERIMENTER_HEADER_SIZE = 8
assert (
    calcsize(OFP_OXM_EXPERIMENTER_HEADER_PACK_STR) == OFP_OXM_EXPERIMENTER_HEADER_SIZE
)

# enum ofp_instruction_type
OFPIT_GOTO_TABLE = 1
OFPIT_WRITE_METADATA = 2
OFPIT_WRITE_ACTIONS = 3
OFPIT_APPLY_ACTIONS = 4
OFPIT_CLEAR_ACTIONS = 5
OFPIT_METER = 6
OFPIT_EXPERIMENTER = 0xFFFF

# struct ofp_instruction_goto_table
OFP_INSTRUCTION_GOTO_TABLE_PACK_STR = "!HHB3x"
OFP_INSTRUCTION_GOTO_TABLE_SIZE = 8
assert calcsize(OFP_INSTRUCTION_GOTO_TABLE_PACK_STR) == OFP_INSTRUCTION_GOTO_TABLE_SIZE

# struct ofp_instruction_write_metadata
OFP_INSTRUCTION_WRITE_METADATA_PACK_STR = "!HH4xQQ"
OFP_INSTRUCTION_WRITE_METADATA_SIZE = 24
assert (
    calcsize(OFP_INSTRUCTION_WRITE_METADATA_PACK_STR)
    == OFP_INSTRUCTION_WRITE_METADATA_SIZE
)

# struct ofp_instruction_actions
OFP_INSTRUCTION_ACTIONS_PACK_STR = "!HH4x"
OFP_INSTRUCTION_ACTIONS_SIZE = 8
assert calcsize(OFP_INSTRUCTION_ACTIONS_PACK_STR) == OFP_INSTRUCTION_ACTIONS_SIZE

# struct ofp_instruction_meter
OFP_INSTRUCTION_METER_PACK_STR = "!HHI"
OFP_INSTRUCTION_METER_SIZE = 8
assert calcsize(OFP_INSTRUCTION_METER_PACK_STR) == OFP_INSTRUCTION_METER_SIZE

# enum ofp_action_type
OFPAT_OUTPUT = 0
OFPAT_COPY_TTL_OUT = 11
OFPAT_COPY_TTL_IN = 12
OFPAT_SET_MPLS_TTL = 15
OFPAT_DEC_MPLS_TTL = 16
OFPAT_PUSH_VLAN = 17
OFPAT_POP_VLAN = 18
OFPAT_PUSH_MPLS = 19
OFPAT_POP_MPLS = 20
OFPAT_SET_QUEUE = 21
OFPAT_GROUP = 22
OFPAT_SET_NW_TTL = 23
OFPAT_DEC_NW_TTL = 24
OFPAT_SET_FIELD = 25
OFPAT_PUSH_PBB = 26
OFPAT_POP_PBB = 27
OFPAT_EXPERIMENTER = 0xFFFF

# struct ofp_action_header
OFP_ACTION_HEADER_PACK_STR = "!HH4x"
OFP_ACTION_HEADER_SIZE = 8
assert calcsize(OFP_ACTION_HEADER_PACK_STR) == OFP_ACTION_HEADER_SIZE

# struct ofp_action_output
OFP_ACTION_OUTPUT_PACK_STR = "!HHIH6x"
OFP_ACTION_OUTPUT_SIZE = 16
assert calcsize(OFP_ACTION_OUTPUT_PACK_STR) == OFP_ACTION_OUTPUT_SIZE

# enum ofp_controller_max_len
OFPCML_MAX = 0xFFE5
OFPCML_NO_BUFFER = 0xFFFF

# struct ofp_action_group
OFP_ACTION_GROUP_PACK_STR = "!HHI"
OFP_ACTION_GROUP_SIZE = 8
assert calcsize(OFP_ACTION_GROUP_PACK_STR) == OFP_ACTION_GROUP_SIZE

# struct ofp_action_set_queue
OFP_ACTION_SET_QUEUE_PACK_STR = "!HHI"
OFP_ACTION_SET_QUEUE_SIZE = 8
assert calcsize(OFP_ACTION_SET_QUEUE_PACK_STR) == OFP_ACTION_SET_QUEUE_SIZE

# struct ofp_action_mpls_ttl
OFP_ACTION_MPLS_TTL_PACK_STR = "!HHB3x"
OFP_ACTION_MPLS_TTL_SIZE = 8
assert calcsize(OFP_ACTION_MPLS_TTL_PACK_STR) == OFP_ACTION_MPLS_TTL_SIZE

# struct ofp_action_nw_ttl
OFP_ACTION_NW_TTL_PACK_STR = "!HHB3x"
OFP_ACTION_NW_TTL_SIZE = 8
assert calcsize(OFP_ACTION_NW_TTL_PACK_STR) == OFP_ACTION_NW_TTL_SIZE

# struct ofp_action_push
OFP_ACTION_PUSH_PACK_STR = "!HHH2x"
OFP_ACTION_PUSH_SIZE = 8
assert calcsize(OFP_ACTION_PUSH_PACK_STR) == OFP_ACTION_PUSH_SIZE

# struct ofp_action_pop_mpls
OFP_ACTION_POP_MPLS_PACK_STR = "!HHH2x"
OFP_ACTION_POP_MPLS_SIZE = 8
assert calcsize(OFP_ACTION_POP_MPLS_PACK_STR) == OFP_ACTION_POP_MPLS_SIZE

# struct ofp_action_set_field
OFP_ACTION_SET_FIELD_PACK_STR = "!HH4x"
OFP_ACTION_SET_FIELD_SIZE = 8
assert calcsize(OFP_ACTION_SET_FIELD_PACK_STR) == OFP_ACTION_SET_FIELD_SIZE

# struct ofp_action_experimenter_header
OFP_ACTION_EXPERIMENTER_HEADER_PACK_STR = "!HHI"
OFP_ACTION_EXPERIMENTER_HEADER_SIZE = 8
assert (
    calcsize(OFP_ACTION_EXPERIMENTER_HEADER_PACK_STR)
    == OFP_ACTION_EXPERIMENTER_HEADER_SIZE
)

# ofp_switch_features
OFP_SWITCH_FEATURES_PACK_STR = "!QIBB2xII"
OFP_SWITCH_FEATURES_SIZE = 32
assert (
    calcsize(OFP_SWITCH_FEATURES_PACK_STR) + OFP_HEADER_SIZE == OFP_SWITCH_FEATURES_SIZE
)

# enum ofp_capabilities
OFPC_FLOW_STATS = 1 << 0
OFPC_TABLE_STATS = 1 << 1
OFPC_PORT_STATS = 1 << 2
OFPC_GROUP_STATS = 1 << 3
OFPC_IP_REASM = 1 << 5
OFPC_QUEUE_STATS = 1 << 6
OFPC_PORT_BLOCKED = 1 << 8

# struct ofp_switch_config
OFP_SWITCH_CONFIG_PACK_STR = "!HH"
OFP_SWITCH_CONFIG_SIZE = 12
assert calcsize(OFP_SWITCH_CONFIG_PACK_STR) + OFP_HEADER_SIZE == OFP_SWITCH_CONFIG_SIZE

# enum ofp_config_flags
OFPC_FRAG_NORMAL = 0
OFPC_FRAG_DROP = 1
OFPC_FRAG_REASM = 2
OFPC_FRAG_MASK = 3

# enum ofp_table
OFPTT_MAX = 0xFE
OFPTT_ALL = 0xFF

# struct ofp_table_mod
OFP_TABLE_MOD_PACK_STR = "!B3xI"
OFP_TABLE_MOD_SIZE = 16
assert calcsize(OFP_TABLE_MOD_PACK_STR) + OFP_HEADER_SIZE == OFP_TABLE_MOD_SIZE

_OFP_FLOW_MOD_PACK_STR0 = "QQBBHHHIIIH2x"
OFP_FLOW_MOD_PACK_STR = "!" + _OFP_FLOW_MOD_PACK_STR0 + _OFP_MATCH_PACK_STR
OFP_FLOW_MOD_PACK_STR0 = "!" + _OFP_FLOW_MOD_PACK_STR0
OFP_FLOW_MOD_SIZE = 56
assert calcsize(OFP_FLOW_MOD_PACK_STR) + OFP_HEADER_SIZE == OFP_FLOW_MOD_SIZE

# enum ofp_flow_mod_command
OFPFC_ADD = 0
OFPFC_MODIFY = 1
OFPFC_MODIFY_STRICT = 2
OFPFC_DELETE = 3
OFPFC_DELETE_STRICT = 4

OFP_DEFAULT_PRIORITY = 0x8000

# enum ofp_flow_mod_flags
OFPFF_SEND_FLOW_REM = 1 << 0
OFPFF_CHECK_OVERLAP = 1 << 1
OFPFF_RESET_COUNTS = 1 << 2
OFPFF_NO_PKT_COUNTS = 1 << 3
OFPFF_NO_BYT_COUNTS = 1 << 4

# struct ofp_group_mod
OFP_GROUP_MOD_PACK_STR = "!HBxI"
OFP_GROUP_MOD_SIZE = 16
assert calcsize(OFP_GROUP_MOD_PACK_STR) + OFP_HEADER_SIZE == OFP_GROUP_MOD_SIZE

# enum ofp_group_mod_command
OFPGC_ADD = 0
OFPGC_MODIFY = 1
OFPGC_DELETE = 2

# enum ofp_group
OFPG_MAX = 0xFFFFFF00
# Fake groups
OFPG_ALL = 0xFFFFFFFC
OFPG_ANY = 0xFFFFFFFF

# enum ofp_group_type
OFPGT_ALL = 0
OFPGT_SELECT = 1
OFPGT_INDIRECT = 2
OFPGT_FF = 3

# struct ofp_bucket
OFP_BUCKET_PACK_STR = "!HHII4x"
OFP_BUCKET_SIZE = 16
assert calcsize(OFP_BUCKET_PACK_STR) == OFP_BUCKET_SIZE

# struct ofp_port_mod
OFP_PORT_MOD_PACK_STR = "!I4x" + OFP_ETH_ALEN_STR + "s2xIII4x"
OFP_PORT_MOD_SIZE = 40
assert calcsize(OFP_PORT_MOD_PACK_STR) + OFP_HEADER_SIZE == OFP_PORT_MOD_SIZE

# struct ofp_meter_mod
OFP_METER_MOD_PACK_STR = "!HHI"
OFP_METER_MOD_SIZE = 16
assert calcsize(OFP_METER_MOD_PACK_STR) + OFP_HEADER_SIZE == OFP_METER_MOD_SIZE

# enum ofp_meter
OFPM_MAX = 0xFFFF0000
OFPM_SLOWPATH = 0xFFFFFFFD
OFPM_CONTROLLER = 0xFFFFFFFE
OFPM_ALL = 0xFFFFFFFF

# enum ofp_meter_mod_command
OFPMC_ADD = 0
OFPMC_MODIFY = 1
OFPMC_DELETE = 2

# enum ofp_meter_flags
OFPMF_KBPS = 1 << 0
OFPMF_PKTPS = 1 << 1
OFPMF_BURST = 1 << 2
OFPMF_STATS = 1 << 3

# struct ofp_meter_band_header
OFP_METER_BAND_HEADER_PACK_STR = "!HHII"
OFP_METER_BAND_HEADER_SIZE = 12
assert calcsize(OFP_METER_BAND_HEADER_PACK_STR) == OFP_METER_BAND_HEADER_SIZE

# enum ofp_meter_band_type
OFPMBT_DROP = 1
OFPMBT_DSCP_REMARK = 2
OFPMBT_EXPERIMENTER = 0xFFFF

# struct ofp_meter_band_drop
OFP_METER_BAND_DROP_PACK_STR = "!HHII4x"
OFP_METER_BAND_DROP_SIZE = 16
assert calcsize(OFP_METER_BAND_DROP_PACK_STR) == OFP_METER_BAND_DROP_SIZE

# struct ofp_meter_band_dscp_remark
OFP_METER_BAND_DSCP_REMARK_PACK_STR = "!HHIIB3x"
OFP_METER_BAND_DSCP_REMARK_SIZE = 16
assert calcsize(OFP_METER_BAND_DSCP_REMARK_PACK_STR) == OFP_METER_BAND_DSCP_REMARK_SIZE

# struct ofp_meter_band_experimenter
OFP_METER_BAND_EXPERIMENTER_PACK_STR = "!HHIII"
OFP_METER_BAND_EXPERIMENTER_SIZE = 16
assert (
    calcsize(OFP_METER_BAND_EXPERIMENTER_PACK_STR) == OFP_METER_BAND_EXPERIMENTER_SIZE
)

# struct ofp_multipart_request
OFP_MULTIPART_REQUEST_PACK_STR = "!HH4x"
OFP_MULTIPART_REQUEST_SIZE = 16
assert (
    calcsize(OFP_MULTIPART_REQUEST_PACK_STR) + OFP_HEADER_SIZE
    == OFP_MULTIPART_REQUEST_SIZE
)

# enum ofp_multipart_request_flags
OFPMPF_REQ_MORE = 1 << 0

# struct ofp_multipart_reply
OFP_MULTIPART_REPLY_PACK_STR = "!HH4x"
OFP_MULTIPART_REPLY_SIZE = 16
assert (
    calcsize(OFP_MULTIPART_REPLY_PACK_STR) + OFP_HEADER_SIZE == OFP_MULTIPART_REPLY_SIZE
)

# enum ofp_multipart_reply_flags
OFPMPF_REPLY_MORE = 1 << 0

# enum ofp_multipart_types
OFPMP_DESC = 0
OFPMP_FLOW = 1
OFPMP_AGGREGATE = 2
OFPMP_TABLE = 3
OFPMP_PORT_STATS = 4
OFPMP_QUEUE = 5
OFPMP_GROUP = 6
OFPMP_GROUP_DESC = 7
OFPMP_GROUP_FEATURES = 8
OFPMP_METER = 9
OFPMP_METER_CONFIG = 10
OFPMP_METER_FEATURES = 11
OFPMP_TABLE_FEATURES = 12
OFPMP_PORT_DESC = 13
OFPMP_EXPERIMENTER = 0xFFFF

# struct ofp_desc
DESC_STR_LEN = 256
DESC_STR_LEN_STR = str(DESC_STR_LEN)
SERIAL_NUM_LEN = 32
SERIAL_NUM_LEN_STR = str(SERIAL_NUM_LEN)
OFP_DESC_PACK_STR = (
    "!"
    + DESC_STR_LEN_STR
    + "s"
    + DESC_STR_LEN_STR
    + "s"
    + DESC_STR_LEN_STR
    + "s"
    + SERIAL_NUM_LEN_STR
    + "s"
    + DESC_STR_LEN_STR
    + "s"
)
OFP_DESC_SIZE = 1056
assert calcsize(OFP_DESC_PACK_STR) == OFP_DESC_SIZE

# struct ofp_flow_stats_request
_OFP_FLOW_STATS_REQUEST_0_PACK_STR = "B3xII4xQQ"
OFP_FLOW_STATS_REQUEST_0_PACK_STR = "!" + _OFP_FLOW_STATS_REQUEST_0_PACK_STR
OFP_FLOW_STATS_REQUEST_0_SIZE = 32
assert calcsize(OFP_FLOW_STATS_REQUEST_0_PACK_STR) == OFP_FLOW_STATS_REQUEST_0_SIZE
OFP_FLOW_STATS_REQUEST_PACK_STR = (
    OFP_FLOW_STATS_REQUEST_0_PACK_STR + _OFP_MATCH_PACK_STR
)
OFP_FLOW_STATS_REQUEST_SIZE = 40
assert calcsize(OFP_FLOW_STATS_REQUEST_PACK_STR) == OFP_FLOW_STATS_REQUEST_SIZE

# struct ofp_flow_stats
_OFP_FLOW_STATS_0_PACK_STR = "HBxIIHHHH4xQQQ"
OFP_FLOW_STATS_0_PACK_STR = "!" + _OFP_FLOW_STATS_0_PACK_STR
OFP_FLOW_STATS_0_SIZE = 48
assert calcsize(OFP_FLOW_STATS_0_PACK_STR) == OFP_FLOW_STATS_0_SIZE
OFP_FLOW_STATS_PACK_STR = OFP_FLOW_STATS_0_PACK_STR + _OFP_MATCH_PACK_STR
OFP_FLOW_STATS_SIZE = 56
assert calcsize(OFP_FLOW_STATS_PACK_STR) == OFP_FLOW_STATS_SIZE

# struct ofp_aggregate_stats_request
_OFP_AGGREGATE_STATS_REQUEST_0_PACK_STR = "B3xII4xQQ"
OFP_AGGREGATE_STATS_REQUEST_0_PACK_STR = "!" + _OFP_AGGREGATE_STATS_REQUEST_0_PACK_STR
OFP_AGGREGATE_STATS_REQUEST_0_SIZE = 32
assert (
    calcsize(OFP_AGGREGATE_STATS_REQUEST_0_PACK_STR)
    == OFP_AGGREGATE_STATS_REQUEST_0_SIZE
)
OFP_AGGREGATE_STATS_REQUEST_PACK_STR = (
    OFP_AGGREGATE_STATS_REQUEST_0_PACK_STR + _OFP_MATCH_PACK_STR
)
OFP_AGGREGATE_STATS_REQUEST_SIZE = 40
assert (
    calcsize(OFP_AGGREGATE_STATS_REQUEST_PACK_STR) == OFP_AGGREGATE_STATS_REQUEST_SIZE
)

# struct ofp_aggregate_stats_reply
OFP_AGGREGATE_STATS_REPLY_PACK_STR = "!QQI4x"
OFP_AGGREGATE_STATS_REPLY_SIZE = 24
assert calcsize(OFP_AGGREGATE_STATS_REPLY_PACK_STR) == OFP_AGGREGATE_STATS_REPLY_SIZE

# struct ofp_table_stats
OFP_TABLE_STATS_PACK_STR = "!B3xIQQ"
OFP_TABLE_STATS_SIZE = 24
assert calcsize(OFP_TABLE_STATS_PACK_STR) == OFP_TABLE_STATS_SIZE

# struct ofp_table_features
OFP_MAX_TABLE_NAME_LEN = 32
OFP_MAX_TABLE_NAME_LEN_STR = str(OFP_MAX_TABLE_NAME_LEN)
OFP_TABLE_FEATURES_PACK_STR = "!HB5x" + OFP_MAX_TABLE_NAME_LEN_STR + "s" + "QQII"
OFP_TABLE_FEATURES_SIZE = 64
assert calcsize(OFP_TABLE_FEATURES_PACK_STR) == OFP_TABLE_FEATURES_SIZE

# enum ofp_table_feature_prop_type
OFPTFPT_INSTRUCTIONS = 0
OFPTFPT_INSTRUCTIONS_MISS = 1
OFPTFPT_NEXT_TABLES = 2
OFPTFPT_NEXT_TABLES_MISS = 3
OFPTFPT_WRITE_ACTIONS = 4
OFPTFPT_WRITE_ACTIONS_MISS = 5
OFPTFPT_APPLY_ACTIONS = 6
OFPTFPT_APPLY_ACTIONS_MISS = 7
OFPTFPT_MATCH = 8
OFPTFPT_WILDCARDS = 10
OFPTFPT_WRITE_SETFIELD = 12
OFPTFPT_WRITE_SETFIELD_MISS = 13
OFPTFPT_APPLY_SETFIELD = 14
OFPTFPT_APPLY_SETFIELD_MISS = 15
OFPTFPT_EXPERIMENTER = 0xFFFE
OFPTFPT_EXPERIMENTER_MISS = 0xFFFF

# struct ofp_table_feature_prop_instructions
OFP_TABLE_FEATURE_PROP_INSTRUCTIONS_PACK_STR = "!HH"
OFP_TABLE_FEATURE_PROP_INSTRUCTIONS_SIZE = 4
assert (
    calcsize(OFP_TABLE_FEATURE_PROP_INSTRUCTIONS_PACK_STR)
    == OFP_TABLE_FEATURE_PROP_INSTRUCTIONS_SIZE
)

# struct ofp_table_feature_prop_next_tables
OFP_TABLE_FEATURE_PROP_NEXT_TABLES_PACK_STR = "!HH"
OFP_TABLE_FEATURE_PROP_NEXT_TABLES_SIZE = 4
assert (
    calcsize(OFP_TABLE_FEATURE_PROP_NEXT_TABLES_PACK_STR)
    == OFP_TABLE_FEATURE_PROP_NEXT_TABLES_SIZE
)

# struct ofp_table_feature_prop_actions
OFP_TABLE_FEATURE_PROP_ACTIONS_PACK_STR = "!HH"
OFP_TABLE_FEATURE_PROP_ACTIONS_SIZE = 4
assert (
    calcsize(OFP_TABLE_FEATURE_PROP_ACTIONS_PACK_STR)
    == OFP_TABLE_FEATURE_PROP_ACTIONS_SIZE
)

# struct ofp_table_feature_prop_oxm
OFP_TABLE_FEATURE_PROP_OXM_PACK_STR = "!HH"
OFP_TABLE_FEATURE_PROP_OXM_SIZE = 4
assert calcsize(OFP_TABLE_FEATURE_PROP_OXM_PACK_STR) == OFP_TABLE_FEATURE_PROP_OXM_SIZE

# struct ofp_port_stats_request
OFP_PORT_STATS_REQUEST_PACK_STR = "!I4x"
OFP_PORT_STATS_REQUEST_SIZE = 8
assert calcsize(OFP_PORT_STATS_REQUEST_PACK_STR) == OFP_PORT_STATS_REQUEST_SIZE

# struct ofp_port_stats
OFP_PORT_STATS_PACK_STR = "!I4xQQQQQQQQQQQQII"
OFP_PORT_STATS_SIZE = 112
assert calcsize(OFP_PORT_STATS_PACK_STR) == OFP_PORT_STATS_SIZE

# struct ofp_queue_stats_request
OFP_QUEUE_STATS_REQUEST_PACK_STR = "!II"
OFP_QUEUE_STATS_REQUEST_SIZE = 8
assert calcsize(OFP_QUEUE_STATS_REQUEST_PACK_STR) == OFP_QUEUE_STATS_REQUEST_SIZE

# struct ofp_queue_stats
OFP_QUEUE_STATS_PACK_STR = "!IIQQQII"
OFP_QUEUE_STATS_SIZE = 40
assert calcsize(OFP_QUEUE_STATS_PACK_STR) == OFP_QUEUE_STATS_SIZE

# struct ofp_group_stats_request
OFP_GROUP_STATS_REQUEST_PACK_STR = "!I4x"
OFP_GROUP_STATS_REQUEST_SIZE = 8
assert calcsize(OFP_GROUP_STATS_REQUEST_PACK_STR) == OFP_GROUP_STATS_REQUEST_SIZE

# struct ofp_group_stats
OFP_GROUP_STATS_PACK_STR = "!H2xII4xQQII"
OFP_GROUP_STATS_SIZE = 40
assert calcsize(OFP_GROUP_STATS_PACK_STR) == OFP_GROUP_STATS_SIZE

# struct ofp_bucket_counter
OFP_BUCKET_COUNTER_PACK_STR = "!QQ"
OFP_BUCKET_COUNTER_SIZE = 16
assert calcsize(OFP_BUCKET_COUNTER_PACK_STR) == OFP_BUCKET_COUNTER_SIZE

# struct ofp_group_desc
OFP_GROUP_DESC_PACK_STR = "!HBxI"
OFP_GROUP_DESC_SIZE = 8
assert calcsize(OFP_GROUP_DESC_PACK_STR) == OFP_GROUP_DESC_SIZE

# struct ofp_group_desc_stats
OFP_GROUP_DESC_STATS_PACK_STR = OFP_GROUP_DESC_PACK_STR
OFP_GROUP_DESC_STATS_SIZE = OFP_GROUP_DESC_SIZE
assert calcsize(OFP_GROUP_DESC_STATS_PACK_STR) == OFP_GROUP_DESC_STATS_SIZE

# struct ofp_group_features
OFP_GROUP_FEATURES_PACK_STR = "!II4I4I"
OFP_GROUP_FEATURES_SIZE = 40
assert calcsize(OFP_GROUP_FEATURES_PACK_STR) == OFP_GROUP_FEATURES_SIZE

# enum ofp_group_capabilities
OFPGFC_SELECT_WEIGHT = 1 << 0
OFPGFC_SELECT_LIVENESS = 1 << 1
OFPGFC_CHAINING = 1 << 2
OFPGFC_CHAINING_CHECKS = 1 << 3

# struct ofp_meter_multipart_request
OFP_METER_MULTIPART_REQUEST_PACK_STR = "!I4x"
OFP_METER_MULTIPART_REQUEST_SIZE = 8
assert (
    calcsize(OFP_METER_MULTIPART_REQUEST_PACK_STR) == OFP_METER_MULTIPART_REQUEST_SIZE
)

# struct ofp_meter_stats
OFP_METER_STATS_PACK_STR = "!IH6xIQQII"
OFP_METER_STATS_SIZE = 40
assert calcsize(OFP_METER_STATS_PACK_STR) == OFP_METER_STATS_SIZE

# struct ofp_meter_band_stats
OFP_METER_BAND_STATS_PACK_STR = "!QQ"
OFP_METER_BAND_STATS_SIZE = 16
assert calcsize(OFP_METER_BAND_STATS_PACK_STR) == OFP_METER_BAND_STATS_SIZE

# struct ofp_meter_config
OFP_METER_CONFIG_PACK_STR = "!HHI"
OFP_METER_CONFIG_SIZE = 8
assert calcsize(OFP_METER_CONFIG_PACK_STR) == OFP_METER_CONFIG_SIZE

# struct ofp_meter_features
OFP_METER_FEATURES_PACK_STR = "!IIIBB2x"
OFP_METER_FEATURES_SIZE = 16
assert calcsize(OFP_METER_FEATURES_PACK_STR) == OFP_METER_FEATURES_SIZE

# struct ofp_experimenter_multipart_header
OFP_EXPERIMENTER_MULTIPART_HEADER_PACK_STR = "!II"
OFP_EXPERIMENTER_MULTIPART_HEADER_SIZE = 8
assert (
    calcsize(OFP_EXPERIMENTER_MULTIPART_HEADER_PACK_STR)
    == OFP_EXPERIMENTER_MULTIPART_HEADER_SIZE
)

# struct ofp_queue_get_config_request
OFP_QUEUE_GET_CONFIG_REQUEST_PACK_STR = "!I4x"
OFP_QUEUE_GET_CONFIG_REQUEST_SIZE = 16
assert (
    calcsize(OFP_QUEUE_GET_CONFIG_REQUEST_PACK_STR) + OFP_HEADER_SIZE
) == OFP_QUEUE_GET_CONFIG_REQUEST_SIZE

# struct ofp_queue_get_config_reply
OFP_QUEUE_GET_CONFIG_REPLY_PACK_STR = "!I4x"
OFP_QUEUE_GET_CONFIG_REPLY_SIZE = 16
assert (
    calcsize(OFP_QUEUE_GET_CONFIG_REPLY_PACK_STR) + OFP_HEADER_SIZE
) == OFP_QUEUE_GET_CONFIG_REPLY_SIZE

# struct ofp_packet_out
OFP_PACKET_OUT_PACK_STR = "!IIH6x"
OFP_PACKET_OUT_SIZE = 24
assert calcsize(OFP_PACKET_OUT_PACK_STR) + OFP_HEADER_SIZE == OFP_PACKET_OUT_SIZE

# struct ofp_role_request
OFP_ROLE_REQUEST_PACK_STR = "!I4xQ"
OFP_ROLE_REQUEST_SIZE = 24
assert calcsize(OFP_ROLE_REQUEST_PACK_STR) + OFP_HEADER_SIZE == OFP_ROLE_REQUEST_SIZE

# enum ofp_controller_role
OFPCR_ROLE_NOCHANGE = 0
OFPCR_ROLE_EQUAL = 1
OFPCR_ROLE_MASTER = 2
OFPCR_ROLE_SLAVE = 3

# struct ofp_async_config
OFP_ASYNC_CONFIG_PACK_STR = "!2I2I2I"
OFP_ASYNC_CONFIG_SIZE = 32
assert calcsize(OFP_ASYNC_CONFIG_PACK_STR) + OFP_HEADER_SIZE == OFP_ASYNC_CONFIG_SIZE

# struct ofp_packet_in
OFP_PACKET_IN_PACK_STR = "!IHBBQ"
OFP_PACKET_IN_SIZE = 32
assert (
    calcsize(OFP_PACKET_IN_PACK_STR) + OFP_MATCH_SIZE + OFP_HEADER_SIZE
    == OFP_PACKET_IN_SIZE
)

# enum ofp_packet_in_reason
OFPR_NO_MATCH = 0
OFPR_ACTION = 1
OFPR_INVALID_TTL = 2

# struct ofp_flow_removed
_OFP_FLOW_REMOVED_PACK_STR0 = "QHBBIIHHQQ"
OFP_FLOW_REMOVED_PACK_STR = "!" + _OFP_FLOW_REMOVED_PACK_STR0 + _OFP_MATCH_PACK_STR
OFP_FLOW_REMOVED_PACK_STR0 = "!" + _OFP_FLOW_REMOVED_PACK_STR0
OFP_FLOW_REMOVED_SIZE = 56
assert calcsize(OFP_FLOW_REMOVED_PACK_STR) + OFP_HEADER_SIZE == OFP_FLOW_REMOVED_SIZE

# enum ofp_flow_removed_reason
OFPRR_IDLE_TIMEOUT = 0
OFPRR_HARD_TIMEOUT = 1
OFPRR_DELETE = 2
OFPRR_GROUP_DELETE = 3

# struct ofp_port_status
OFP_PORT_STATUS_PACK_STR = "!B7x" + _OFP_PORT_PACK_STR
OFP_PORT_STATUS_DESC_OFFSET = OFP_HEADER_SIZE + 8
OFP_PORT_STATUS_SIZE = 80
assert calcsize(OFP_PORT_STATUS_PACK_STR) + OFP_HEADER_SIZE == OFP_PORT_STATUS_SIZE

# enum ofp_port_reason
OFPPR_ADD = 0
OFPPR_DELETE = 1
OFPPR_MODIFY = 2

# OFPMP_EXPERIMENTER
# struct onf_experimenter_multipart_msg
ONFMP_FLOW_MONITOR = 1870

# onf_flow_monitor_request
ONF_FLOW_MONITOR_REQUEST_PACK_STR = "!IHHIB3x"
ONF_FLOW_MONITOR_REQUEST_SIZE = 16
assert calcsize(ONF_FLOW_MONITOR_REQUEST_PACK_STR) == ONF_FLOW_MONITOR_REQUEST_SIZE

ONFFMF_INITIAL = 1 << 0
ONFFMF_ADD = 1 << 1
ONFFMF_DELETE = 1 << 2
ONFFMF_MODIFY = 1 << 3
ONFFMF_ACTIONS = 1 << 4
ONFFMF_OWN = 1 << 5

# onf_flow_update_header
ONF_FLOW_UPDATE_HEADER_PACK_STR = "!HH"
ONF_FLOW_UPDATE_HEADER_SIZE = 4
assert calcsize(ONF_FLOW_UPDATE_HEADER_PACK_STR) == ONF_FLOW_UPDATE_HEADER_SIZE

ONF_FLOW_UPDATE_FULL_PACK_STR = "!HHHHHBxQ"
ONF_FLOW_UPDATE_FULL_SIZE = 24 - ONF_FLOW_UPDATE_HEADER_SIZE
assert calcsize(ONF_FLOW_UPDATE_FULL_PACK_STR) == ONF_FLOW_UPDATE_FULL_SIZE

# xid
ONF_FLOW_UPDATE_ABBREV_PACK_STR = "!I"
ONF_FLOW_UPDATE_ABBREV_SIZE = 8 - ONF_FLOW_UPDATE_HEADER_SIZE
assert calcsize(ONF_FLOW_UPDATE_ABBREV_PACK_STR) == ONF_FLOW_UPDATE_ABBREV_SIZE

# enum onf_flow_udpate_event
ONFFME_ADDED = 0
ONFFME_DELETED = 1
ONFFME_MODIFIED = 2
ONFFME_ABBREV = 3

# enum onf_flow_monitor_msg_type
ONFT_FLOW_MONITOR_CANCEL = 1870
ONFT_FLOW_MONITOR_PAUSED = 1871
ONFT_FLOW_MONITOR_RESUMED = 1872

# EXT-230 Bundle extension

# enum onf_exp_type
ONF_ET_BUNDLE_CONTROL = 2300
ONF_ET_BUNDLE_ADD_MESSAGE = 2301

ONF_BUNDLE_CTRL_PACK_STR = "!IHH"
ONF_BUNDLE_CTRL_SIZE = 8
assert calcsize(ONF_BUNDLE_CTRL_PACK_STR) == ONF_BUNDLE_CTRL_SIZE

ONF_BUNDLE_ADD_MSG_PACK_STR = "!I2xH"
ONF_BUNDLE_ADD_MSG_SIZE = 16 - OFP_HEADER_SIZE
assert calcsize(ONF_BUNDLE_ADD_MSG_PACK_STR) == ONF_BUNDLE_ADD_MSG_SIZE

# enum onf_bundle_ctrl_type
ONF_BCT_OPEN_REQUEST = 0
ONF_BCT_OPEN_REPLY = 1
ONF_BCT_CLOSE_REQUEST = 2
ONF_BCT_CLOSE_REPLY = 3
ONF_BCT_COMMIT_REQUEST = 4
ONF_BCT_COMMIT_REPLY = 5
ONF_BCT_DISCARD_REQUEST = 6
ONF_BCT_DISCARD_REPLY = 7

# enum onf_bundle_flags
ONF_BF_ATOMIC = 1 << 0
ONF_BF_ORDERED = 1 << 1

# enum onf_bundle_prop_type
ONF_ET_BPT_EXPERIMENTER = 0xFFFF

# struct ofp_error_msg
OFP_ERROR_MSG_PACK_STR = "!HH"
OFP_ERROR_MSG_SIZE = 12
assert calcsize(OFP_ERROR_MSG_PACK_STR) + OFP_HEADER_SIZE == OFP_ERROR_MSG_SIZE

# enum ofp_error_type
OFPET_HELLO_FAILED = 0
OFPET_BAD_REQUEST = 1
OFPET_BAD_ACTION = 2
OFPET_BAD_INSTRUCTION = 3
OFPET_BAD_MATCH = 4
OFPET_FLOW_MOD_FAILED = 5
OFPET_GROUP_MOD_FAILED = 6
OFPET_PORT_MOD_FAILED = 7
OFPET_TABLE_MOD_FAILED = 8
OFPET_QUEUE_OP_FAILED = 9
OFPET_SWITCH_CONFIG_FAILED = 10
OFPET_ROLE_REQUEST_FAILED = 11
OFPET_METER_MOD_FAILED = 12
OFPET_TABLE_FEATURES_FAILED = 13
OFPET_EXPERIMENTER = 0xFFFF

# enum ofp_hello_failed_code
OFPHFC_INCOMPATIBLE = 0
OFPHFC_EPERM = 1

# enum ofp_bad_request_code
OFPBRC_BAD_VERSION = 0
OFPBRC_BAD_TYPE = 1
OFPBRC_BAD_MULTIPART = 2
OFPBRC_BAD_EXPERIMENTER = 3
OFPBRC_BAD_EXP_TYPE = 4
OFPBRC_EPERM = 5
OFPBRC_BAD_LEN = 6
OFPBRC_BUFFER_EMPTY = 7
OFPBRC_BUFFER_UNKNOWN = 8
OFPBRC_BAD_TABLE_ID = 9
OFPBRC_IS_SLAVE = 10
OFPBRC_BAD_PORT = 11
OFPBRC_BAD_PACKET = 12
OFPBRC_MULTIPART_BUFFER_OVERFLOW = 13

# enum ofp_bad_action_code
OFPBAC_BAD_TYPE = 0
OFPBAC_BAD_LEN = 1
OFPBAC_BAD_EXPERIMENTER = 2
OFPBAC_BAD_EXP_TYPE = 3
OFPBAC_BAD_OUT_PORT = 4
OFPBAC_BAD_ARGUMENT = 5
OFPBAC_EPERM = 6
OFPBAC_TOO_MANY = 7
OFPBAC_BAD_QUEUE = 8
OFPBAC_BAD_OUT_GROUP = 9
OFPBAC_MATCH_INCONSISTENT = 10
OFPBAC_UNSUPPORTED_ORDER = 11
OFPBAC_BAD_TAG = 12
OFPBAC_BAD_SET_TYPE = 13
OFPBAC_BAD_SET_LEN = 14
OFPBAC_BAD_SET_ARGUMENT = 15

# enum ofp_bad_instruction_code
OFPBIC_UNKNOWN_INST = 0
OFPBIC_UNSUP_INST = 1
OFPBIC_BAD_TABLE_ID = 2
OFPBIC_UNSUP_METADATA = 3
OFPBIC_UNSUP_METADATA_MASK = 4
OFPBIC_BAD_EXPERIMENTER = 5
OFPBIC_BAD_EXP_TYPE = 6
OFPBIC_BAD_LEN = 7
OFPBIC_EPERM = 8

# enum ofp_bad_match_code
OFPBMC_BAD_TYPE = 0
OFPBMC_BAD_LEN = 1
OFPBMC_BAD_TAG = 2
OFPBMC_BAD_DL_ADDR_MASK = 3
OFPBMC_BAD_NW_ADDR_MASK = 4
OFPBMC_BAD_WILDCARDS = 5
OFPBMC_BAD_FIELD = 6
OFPBMC_BAD_VALUE = 7
OFPBMC_BAD_MASK = 8
OFPBMC_BAD_PREREQ = 9
OFPBMC_DUP_FIELD = 10
OFPBMC_EPERM = 11

# enum ofp_flow_mod_failed_code
OFPFMFC_UNKNOWN = 0
OFPFMFC_TABLE_FULL = 1
OFPFMFC_BAD_TABLE_ID = 2
OFPFMFC_OVERLAP = 3
OFPFMFC_EPERM = 4
OFPFMFC_BAD_TIMEOUT = 5
OFPFMFC_BAD_COMMAND = 6
OFPFMFC_BAD_FLAGS = 7

# enum ofp_group_mod_failed_code
OFPGMFC_GROUP_EXISTS = 0
OFPGMFC_INVALID_GROUP = 1
OFPGMFC_WEIGHT_UNSUPPORTED = 2
OFPGMFC_OUT_OF_GROUPS = 3
OFPGMFC_OUT_OF_BUCKETS = 4
OFPGMFC_CHAINING_UNSUPPORTED = 5
OFPGMFC_WATCH_UNSUPPORTED = 6
OFPGMFC_LOOP = 7
OFPGMFC_UNKNOWN_GROUP = 8
OFPGMFC_CHAINED_GROUP = 9
OFPGMFC_BAD_TYPE = 10
OFPGMFC_BAD_COMMAND = 11
OFPGMFC_BAD_BUCKET = 12
OFPGMFC_BAD_WATCH = 13
OFPGMFC_EPERM = 14

# enum ofp_port_mod_failed_code
OFPPMFC_BAD_PORT = 0
OFPPMFC_BAD_HW_ADDR = 1
OFPPMFC_BAD_CONFIG = 2
OFPPMFC_BAD_ADVERTISE = 3
OFPPMFC_EPERM = 4

# enum ofp_table_mod_failed_code
OFPTMFC_BAD_TABLE = 0
OFPTMFC_BAD_CONFIG = 1
OFPTMFC_EPERM = 2

# enum ofp_queue_op_failed_code
OFPQOFC_BAD_PORT = 0
OFPQOFC_BAD_QUEUE = 1
OFPQOFC_EPERM = 2

# enum ofp_switch_config_failed_code
OFPSCFC_BAD_FLAGS = 0
OFPSCFC_BAD_LEN = 1
OFPQCFC_EPERM = 2
OFPSCFC_EPERM = 2

# enum ofp_role_request_failed_code
OFPRRFC_STALE = 0
OFPRRFC_UNSUP = 1
OFPRRFC_BAD_ROLE = 2

# enum ofp_meter_mod_failed_code
OFPMMFC_UNKNOWN = 0
OFPMMFC_METER_EXISTS = 1
OFPMMFC_INVALID_METER = 2
OFPMMFC_UNKNOWN_METER = 3
OFPMMFC_BAD_COMMAND = 4
OFPMMFC_BAD_FLAGS = 5
OFPMMFC_BAD_RATE = 6
OFPMMFC_BAD_BURST = 7
OFPMMFC_BAD_BAND = 8
OFPMMFC_BAD_BAND_VALUE = 9
OFPMMFC_OUT_OF_METERS = 10
OFPMMFC_OUT_OF_BANDS = 11

# enum ofp_table_features_failed_code
OFPTFFC_BAD_TABLE = 0
OFPTFFC_BAD_METADATA = 1
OFPTFFC_BAD_TYPE = 2
OFPTFFC_BAD_LEN = 3
OFPTFFC_BAD_ARGUMENT = 4
OFPTFFC_EPERM = 5

# struct ofp_error_experimenter_msg
OFP_ERROR_EXPERIMENTER_MSG_PACK_STR = "!HHI"
OFP_ERROR_EXPERIMENTER_MSG_SIZE = 16
assert (
    calcsize(OFP_ERROR_EXPERIMENTER_MSG_PACK_STR) + OFP_HEADER_SIZE
) == OFP_ERROR_EXPERIMENTER_MSG_SIZE

# struct ofp_experimenter_header
OFP_EXPERIMENTER_HEADER_PACK_STR = "!II"
OFP_EXPERIMENTER_HEADER_SIZE = 16
assert (
    calcsize(OFP_EXPERIMENTER_HEADER_PACK_STR) + OFP_HEADER_SIZE
    == OFP_EXPERIMENTER_HEADER_SIZE
)

ONFERR_ET_UNKNOWN = 2300
ONFERR_ET_EPERM = 2301
ONFERR_ET_BAD_ID = 2302
ONFERR_ET_BUNDLE_EXIST = 2303
ONFERR_ET_BUNDLE_CLOSED = 2304
ONFERR_ET_OUT_OF_BUNDLES = 2305
ONFERR_ET_BAD_TYPE = 2306
ONFERR_ET_BAD_FLAGS = 2307
ONFERR_ET_MSG_BAD_LEN = 2308
ONFERR_ET_MSG_BAD_XID = 2309
ONFERR_ET_MSG_UNSUP = 2310
ONFERR_ET_MSG_CONFLICT = 2311
ONFERR_ET_MSG_TOO_MANY = 2312
ONFERR_ET_FAILED = 2313
ONFERR_ET_TIMEOUT = 2314
ONFERR_ET_BUNDLE_IN_PROGRESS = 2315
ONFERR_ET_CANT_SYNC = 2320
ONFERR_ET_BAD_PRIORITY = 2360
ONFERR_ET_ASYNC_INVALUD = 2370
ONFERR_ET_ASYNC_UNSUPPORTED = 2371
ONFERR_ET_ASYNC_EPERM = 2372
ONFERR_DUP_INSTRUCTION = 2600
ONFERR_ET_MPART_REQUEST_TIMEOUT = 2640
ONFERR_ET_MPART_REPLY_TIMEOUT = 2641

# struct ofp_hello
OFP_HELLO_HEADER_SIZE = 8

# struct ofp_hello_elem_header
OFP_HELLO_ELEM_HEADER_PACK_STR = "!HH"
OFP_HELLO_ELEM_HEADER_SIZE = 4
assert calcsize(OFP_HELLO_ELEM_HEADER_PACK_STR) == OFP_HELLO_ELEM_HEADER_SIZE

# enum ofp_hello_elem_type
OFPHET_VERSIONBITMAP = 1

# struct ofp_hello_elem_versionbitmap
OFP_HELLO_ELEM_VERSIONBITMAP_HEADER_PACK_STR = "!HH"
OFP_HELLO_ELEM_VERSIONBITMAP_HEADER_SIZE = 4
assert (
    calcsize(OFP_HELLO_ELEM_VERSIONBITMAP_HEADER_PACK_STR)
    == OFP_HELLO_ELEM_VERSIONBITMAP_HEADER_SIZE
)

# OXM

# OXM TLV header helpers


def _oxm_tlv_header(class_, field, hasmask, length):
    """Pack an OXM TLV header from its class, field, hasmask and length."""
    return (class_ << 16) | (field << 9) | (hasmask << 8) | length


def oxm_tlv_header(field, length):
    """OXM TLV header for an exact match on an OpenFlow basic field."""
    return _oxm_tlv_header(OFPXMC_OPENFLOW_BASIC, field, 0, length)


def oxm_tlv_header_w(field, length):
    """OXM TLV header for a masked match on an OpenFlow basic field."""
    return _oxm_tlv_header(OFPXMC_OPENFLOW_BASIC, field, 1, length * 2)


def oxm_tlv_header_extract_hasmask(header):
    """Return the hasmask bit of an OXM TLV header."""
    return (header >> 8) & 1


def oxm_tlv_header_extract_length(header):
    """Return the unmasked value length encoded in an OXM TLV header."""
    if oxm_tlv_header_extract_hasmask(header):
        return (header & 0xFF) // 2
    return header & 0xFF


# struct ofp_prop_experimenter (implementation defined, common to ofp_*_prop_experimenter)
OFP_PROP_EXPERIMENTER_PACK_STR = "!HHII"
OFP_PROP_EXPERIMENTER_SIZE = 12
assert calcsize(OFP_PROP_EXPERIMENTER_PACK_STR) == OFP_PROP_EXPERIMENTER_SIZE

# protocol version and transaction id
OFP_VERSION = 0x04
MAX_XID = 0xFFFFFFFF
OFP_NO_BUFFER = 0xFFFFFFFF

# transport ports
OFP_TCP_PORT = 6653
OFP_SSL_PORT = 6653
OFP_TCP_PORT_OLD = 6633
OFP_SSL_PORT_OLD = 6633

# vendor/experimenter ids
NX_EXPERIMENTER_ID = 0x00002320
NX_NSH_EXPERIMENTER_ID = 0x005AD650
BSN_EXPERIMENTER_ID = 0x005C16C7
ONF_EXPERIMENTER_ID = 0x4F4E4600
