"""Every OpenFlow 1.3 structure, in one module.

The wire types live in :mod:`c65of.ofproto.base` (message framework, match,
actions, instructions), :mod:`c65of.ofproto.messages` and
:mod:`c65of.ofproto.multipart`. This module re-exports all of them, so a
consumer imports one name and has the whole protocol.

The lists below are generated from those three modules rather than
maintained by hand.
"""

# Copyright (C) 2026 The c65sdn Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# The codec introspects the layout configuration of the classes it serves.
# pylint: disable=protected-access
# name -> class, for resolving {"ClassName": {...}} in JSON dicts. A name can
# be claimed by more than one class -- icmp.echo and icmpv6.echo, say -- in
# which case the first registration is what a bare lookup finds and
# ``cls_from_jsondict_key`` disambiguates by the enclosing class's module.

from c65of.ofproto.base import (
    ACTIONS,
    INSTRUCTIONS,
    METER_BANDS,
    MsgBase,
    OFPAction,
    OFPActionCopyTtlIn,
    OFPActionCopyTtlOut,
    OFPActionDecMplsTtl,
    OFPActionDecNwTtl,
    OFPActionExperimenter,
    OFPActionGroup,
    OFPActionOutput,
    OFPActionPopMpls,
    OFPActionPopPbb,
    OFPActionPopVlan,
    OFPActionPushMpls,
    OFPActionPushPbb,
    OFPActionPushVlan,
    OFPActionSetField,
    OFPActionSetMplsTtl,
    OFPActionSetNwTtl,
    OFPActionSetQueue,
    OFPInstruction,
    OFPInstructionActions,
    OFPInstructionGotoTable,
    OFPInstructionMeter,
    OFPInstructionWriteMetadata,
    OFPMatch,
    OFPPort,
    OFPTruncatedMessage,
    OFPUnknownVersion,
    QUEUE_PROPS,
    header,
    msg,
    ofp_msg_from_jsondict,
    round_up,
)

from c65of.ofproto.messages import (
    OFPBarrierReply,
    OFPBarrierRequest,
    OFPBucket,
    OFPEchoReply,
    OFPEchoRequest,
    OFPErrorExperimenterMsg,
    OFPErrorMsg,
    OFPExperimenter,
    OFPFeaturesRequest,
    OFPFlowMod,
    OFPFlowRemoved,
    OFPGetAsyncReply,
    OFPGetAsyncRequest,
    OFPGetConfigReply,
    OFPGetConfigRequest,
    OFPGroupMod,
    OFPHello,
    OFPHelloElemVersionBitmap,
    OFPMeterBandDrop,
    OFPMeterBandDscpRemark,
    OFPMeterBandExperimenter,
    OFPMeterBandHeader,
    OFPMeterMod,
    OFPPacketIn,
    OFPPacketOut,
    OFPPacketQueue,
    OFPPortMod,
    OFPPortStatus,
    OFPQueueGetConfigReply,
    OFPQueueGetConfigRequest,
    OFPQueueProp,
    OFPQueuePropExperimenter,
    OFPQueuePropHeader,
    OFPQueuePropMaxRate,
    OFPQueuePropMinRate,
    OFPRoleReply,
    OFPRoleRequest,
    OFPSetAsync,
    OFPSetConfig,
    OFPSwitchFeatures,
    OFPTableMod,
)

from c65of.ofproto.multipart import (
    OFPActionId,
    OFPAggregateStats,
    OFPAggregateStatsReply,
    OFPAggregateStatsRequest,
    OFPBucketCounter,
    OFPDescStats,
    OFPDescStatsReply,
    OFPDescStatsRequest,
    OFPExperimenterMultipart,
    OFPExperimenterOxmId,
    OFPExperimenterStatsReply,
    OFPExperimenterStatsRequest,
    OFPExperimenterStatsRequestBase,
    OFPFlowStats,
    OFPFlowStatsReply,
    OFPFlowStatsRequest,
    OFPFlowStatsRequestBase,
    OFPGroupDescStats,
    OFPGroupDescStatsReply,
    OFPGroupDescStatsRequest,
    OFPGroupFeaturesStats,
    OFPGroupFeaturesStatsReply,
    OFPGroupFeaturesStatsRequest,
    OFPGroupStats,
    OFPGroupStatsReply,
    OFPGroupStatsRequest,
    OFPInstructionId,
    OFPMeterBandStats,
    OFPMeterConfigStats,
    OFPMeterConfigStatsReply,
    OFPMeterConfigStatsRequest,
    OFPMeterFeaturesStats,
    OFPMeterFeaturesStatsReply,
    OFPMeterFeaturesStatsRequest,
    OFPMeterStats,
    OFPMeterStatsReply,
    OFPMeterStatsRequest,
    OFPMultipartReply,
    OFPMultipartRequest,
    OFPOxmId,
    OFPPortDescStatsReply,
    OFPPortDescStatsRequest,
    OFPPortStats,
    OFPPortStatsReply,
    OFPPortStatsRequest,
    OFPQueueStats,
    OFPQueueStatsReply,
    OFPQueueStatsRequest,
    OFPTableFeatureProp,
    OFPTableFeaturePropActions,
    OFPTableFeaturePropExperimenter,
    OFPTableFeaturePropInstructions,
    OFPTableFeaturePropNextTables,
    OFPTableFeaturePropOxm,
    OFPTableFeaturePropUnknown,
    OFPTableFeaturesStats,
    OFPTableFeaturesStatsReply,
    OFPTableFeaturesStatsRequest,
    OFPTableStats,
    OFPTableStatsReply,
    OFPTableStatsRequest,
    ONFFlowMonitorRequest,
    ONFFlowMonitorStatsRequest,
)

from c65of.ofproto.nx import (
    NXAction,
    NXActionCT,
    NXActionCTClear,
    NXActionNAT,
    NXActionUnknown,
)

__all__ = [
    "ACTIONS",
    "INSTRUCTIONS",
    "METER_BANDS",
    "MsgBase",
    "NXAction",
    "NXActionCT",
    "NXActionCTClear",
    "NXActionNAT",
    "NXActionUnknown",
    "OFPAction",
    "OFPActionCopyTtlIn",
    "OFPActionCopyTtlOut",
    "OFPActionDecMplsTtl",
    "OFPActionDecNwTtl",
    "OFPActionExperimenter",
    "OFPActionGroup",
    "OFPActionId",
    "OFPActionOutput",
    "OFPActionPopMpls",
    "OFPActionPopPbb",
    "OFPActionPopVlan",
    "OFPActionPushMpls",
    "OFPActionPushPbb",
    "OFPActionPushVlan",
    "OFPActionSetField",
    "OFPActionSetMplsTtl",
    "OFPActionSetNwTtl",
    "OFPActionSetQueue",
    "OFPAggregateStats",
    "OFPAggregateStatsReply",
    "OFPAggregateStatsRequest",
    "OFPBarrierReply",
    "OFPBarrierRequest",
    "OFPBucket",
    "OFPBucketCounter",
    "OFPDescStats",
    "OFPDescStatsReply",
    "OFPDescStatsRequest",
    "OFPEchoReply",
    "OFPEchoRequest",
    "OFPErrorExperimenterMsg",
    "OFPErrorMsg",
    "OFPExperimenter",
    "OFPExperimenterMultipart",
    "OFPExperimenterOxmId",
    "OFPExperimenterStatsReply",
    "OFPExperimenterStatsRequest",
    "OFPExperimenterStatsRequestBase",
    "OFPFeaturesRequest",
    "OFPFlowMod",
    "OFPFlowRemoved",
    "OFPFlowStats",
    "OFPFlowStatsReply",
    "OFPFlowStatsRequest",
    "OFPFlowStatsRequestBase",
    "OFPGetAsyncReply",
    "OFPGetAsyncRequest",
    "OFPGetConfigReply",
    "OFPGetConfigRequest",
    "OFPGroupDescStats",
    "OFPGroupDescStatsReply",
    "OFPGroupDescStatsRequest",
    "OFPGroupFeaturesStats",
    "OFPGroupFeaturesStatsReply",
    "OFPGroupFeaturesStatsRequest",
    "OFPGroupMod",
    "OFPGroupStats",
    "OFPGroupStatsReply",
    "OFPGroupStatsRequest",
    "OFPHello",
    "OFPHelloElemVersionBitmap",
    "OFPInstruction",
    "OFPInstructionActions",
    "OFPInstructionGotoTable",
    "OFPInstructionId",
    "OFPInstructionMeter",
    "OFPInstructionWriteMetadata",
    "OFPMatch",
    "OFPMeterBandDrop",
    "OFPMeterBandDscpRemark",
    "OFPMeterBandExperimenter",
    "OFPMeterBandHeader",
    "OFPMeterBandStats",
    "OFPMeterConfigStats",
    "OFPMeterConfigStatsReply",
    "OFPMeterConfigStatsRequest",
    "OFPMeterFeaturesStats",
    "OFPMeterFeaturesStatsReply",
    "OFPMeterFeaturesStatsRequest",
    "OFPMeterMod",
    "OFPMeterStats",
    "OFPMeterStatsReply",
    "OFPMeterStatsRequest",
    "OFPMultipartReply",
    "OFPMultipartRequest",
    "OFPOxmId",
    "OFPPacketIn",
    "OFPPacketOut",
    "OFPPacketQueue",
    "OFPPort",
    "OFPPortDescStatsReply",
    "OFPPortDescStatsRequest",
    "OFPPortMod",
    "OFPPortStats",
    "OFPPortStatsReply",
    "OFPPortStatsRequest",
    "OFPPortStatus",
    "OFPQueueGetConfigReply",
    "OFPQueueGetConfigRequest",
    "OFPQueueProp",
    "OFPQueuePropExperimenter",
    "OFPQueuePropHeader",
    "OFPQueuePropMaxRate",
    "OFPQueuePropMinRate",
    "OFPQueueStats",
    "OFPQueueStatsReply",
    "OFPQueueStatsRequest",
    "OFPRoleReply",
    "OFPRoleRequest",
    "OFPSetAsync",
    "OFPSetConfig",
    "OFPSwitchFeatures",
    "OFPTableFeatureProp",
    "OFPTableFeaturePropActions",
    "OFPTableFeaturePropExperimenter",
    "OFPTableFeaturePropInstructions",
    "OFPTableFeaturePropNextTables",
    "OFPTableFeaturePropOxm",
    "OFPTableFeaturePropUnknown",
    "OFPTableFeaturesStats",
    "OFPTableFeaturesStatsReply",
    "OFPTableFeaturesStatsRequest",
    "OFPTableMod",
    "OFPTableStats",
    "OFPTableStatsReply",
    "OFPTableStatsRequest",
    "OFPTruncatedMessage",
    "OFPUnknownVersion",
    "ONFFlowMonitorRequest",
    "ONFFlowMonitorStatsRequest",
    "QUEUE_PROPS",
    "header",
    "msg",
    "ofp_msg_from_jsondict",
    "round_up",
]
